{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import pickle\n",
    "from helper_functions import Helper\n",
    "from helper_functions import Coinmetrics"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "# TODO: taxonomy?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "if __name__ == \"__main__\":\n",
    "    # set args\n",
    "    CW_IN_FP = '../data/derived/cm_to_coinapi_cw.pkl'\n",
    "    ASSET_IN_FP = '../data/clean/asset_universe_dict.pickle'\n",
    "    CM_API_FP = '../../admin/coinmetrics.txt'\n",
    "    BASE_URL = 'https://api.coinmetrics.io/v4/'\n",
    "    PANEL_OUT_FP = '../data/raw/coinmetrics_panel_hourly.pkl'\n",
    "    MACRO_OUT_FP = '../data/raw/coinmetrics_macro_hourly.pkl'\n",
    "    TARGET_US_EXCHANGES = ['binance.us',  'bitstamp', 'coinbase', 'crypto.com', 'ftx.us', \n",
    "        'gemini', 'kraken', 'kucoin']\n",
    "    TARGET_EXCHANGE_METRICS = ['open_interest_reported_future_usd', 'volume_reported_future_usd_1h', 'volume_reported_spot_usd_1h']\n",
    "    TARGET_FREQ = '1h'\n",
    "    STUDY_START = '2016-07-01'\n",
    "    STUDY_END = '2023-01-03'\n",
    "    TARGET_METRICS = ['AdrActCnt', 'AdrActContCnt', 'AdrActRecCnt', 'AdrActSentCnt', 'AdrBalCnt',\n",
    "        'AdrBalUSD100Cnt', 'AdrBalUSD100KCnt', 'AdrBalUSD10Cnt', 'AdrBalUSD10KCnt', 'AdrBalUSD10MCnt',\n",
    "        'AdrBalUSD1Cnt', 'AdrBalUSD1KCnt', 'AdrBalUSD1MCnt', 'CapAct1yrUSD',\n",
    "        'CapFutExp10yrUSD', 'CapMVRVCur', 'CapMVRVFF', 'CapMrktCurUSD', 'CapMrktEstUSD', 'CapMrktFFUSD',\n",
    "        'CapRealUSD', 'ContERC1155Cnt', 'ContERC20Cnt', 'ContERC721Cnt',\n",
    "        'DiffMean', 'FeeMeanUSD', 'FeeMedUSD', 'FeeRevPct', 'FeeTotUSD', 'FlowInExInclUSD', 'FlowInExUSD',\n",
    "        'FlowMinerIn0HopAllUSD', 'FlowMinerIn1HopAllUSD', 'FlowMinerNet0HopAllUSD', 'FlowMinerNet1HopAllUSD',\n",
    "        'FlowMinerOut0HopAllUSD', 'FlowMinerOut1HopAllUSD', 'FlowOutExInclUSD', 'FlowOutExUSD', 'FlowTfrFromExCnt',\n",
    "        'FlowTfrFromExInclCnt', 'FlowTfrToExCnt', 'FlowTfrToExInclCnt', 'FlowToCLCont', 'GasUsedTx', 'GasUsedTxMean',\n",
    "        'HashRate', 'IssContNtv', 'IssContPctAnn', 'IssContPctDay', 'IssContUSD', 'IssTotUSD', 'MCRC', 'MCTC',\n",
    "        'MOMR', 'MRI0HopAll30d', 'MRI1HopAll30d', 'NDF', 'NVTAdj', 'NVTAdjFF', 'PriceUSD', 'PuellMulCont', 'PuellMulRev',\n",
    "        'PuellMulTot', 'RCTC', 'RVTAdj', 'ReferenceRateUSD', 'RevAllTimeUSD', 'RevHash1yAvgNtv', 'RevHash1yAvgUSD',\n",
    "        'RevHashUSD', 'RevUSD', 'SER', 'SOPR', 'SOPROut', 'SenderCntCLCont', 'SenderTotCLCont', 'SplyAct10yr',\n",
    "        'SplyAct180d', 'SplyAct1d', 'SplyAct1yr', 'SplyAct2yr', 'SplyAct30d', 'SplyAct3yr', 'SplyAct4yr', 'SplyAct5yr',\n",
    "        'SplyAct7d', 'SplyAct90d', 'SplyActEver', 'SplyActPct1yr', 'SplyAdrBalUSD1', 'SplyAdrBalUSD10',\n",
    "        'SplyAdrBalUSD100', 'SplyAdrBalUSD100K', 'SplyAdrBalUSD10K', 'SplyAdrBalUSD10M', 'SplyAdrBalUSD1K',\n",
    "        'SplyAdrBalUSD1M', 'SplyAdrTop100', 'SplyAdrTop10Pct', 'SplyAdrTop1Pct', 'SplyBurntUSD', 'SplyContUSD',\n",
    "        'SplyCur', 'SplyExUSD', 'SplyExpFut10yr', 'SplyFF', 'SplyMiner0HopAllUSD', 'SplyMiner1HopAllUSD',\n",
    "        'SplyRvv180d', 'SplyRvv1yr', 'SplyRvv2yr', 'SplyRvv30d', 'SplyRvv3yr', 'SplyRvv4yr', 'SplyRvv5yr', \n",
    "        'SplyRvv7d', 'SplyRvv90d', 'SplyUTXOLoss', 'SplyUTXOProf', 'TxCnt', 'TxTfrCnt', 'TxTfrValAdjUSD',    \n",
    "        'TxTfrValContCallUSD', 'TxTfrValDayDst', 'TxTfrValDayDstMean', 'TxTfrValMeanUSD', 'TxTfrValMedUSD',\n",
    "        'TxTfrValNtv', 'TxTfrValRecNtv', 'TxTfrValSentNtv', 'TxTfrValUSD', 'UTXOAgeMean', 'UTXOAgeMed', \n",
    "        'UTXOAgeValMean', 'UTXOCnt', 'UTXODay', 'UTXOLossCnt', 'UTXOLossUnrealUSD', 'UTXOProfCnt',\n",
    "        'UTXOProfUnrealUSD', 'VelAct1yr', 'VelCur1yr', 'WalActCnt', 'WalActRecCnt', 'WalActSentCnt', 'WalBalCnt',\n",
    "        'mempool_count', 'mempool_fee', 'mempool_fee_mean', 'mempool_fee_median', 'mempool_feerate_mean',  \n",
    "        'mempool_feerate_median', 'mempool_output_value', 'mempool_size', 'mempool_vsize', \n",
    "        'mining_reward_mean', 'mining_reward_spread']\n",
    "    \n",
    "    # import api key\n",
    "    with open(CM_API_FP) as f:\n",
    "        API_KEY = f.readlines()\n",
    "        API_KEY = API_KEY[0].strip()\n",
    "    BASE_PARAMS = {'api_key': API_KEY}\n",
    "\n",
    "    # Import asset universe and cw\n",
    "    cw_df = pd.read_pickle(CW_IN_FP)\n",
    "    with open(ASSET_IN_FP, \"rb\") as f:\n",
    "        asset_universe_dict = pickle.load(f)\n",
    "    asset_universe = Helper.findUniqueAssets(asset_universe_dict)\n",
    "\n",
    "    # Pull info on assets\n",
    "    assets_df = Coinmetrics.pullAssetInfo(BASE_URL, BASE_PARAMS, asset_universe+['usdt', 'usdc'])\n",
    "\n",
    "    # pull meta data on target exchanges\n",
    "    exchanges_df = Coinmetrics.pullExchangeInfo(BASE_URL, BASE_PARAMS, TARGET_US_EXCHANGES)\n",
    "\n",
    "    # pull meta data markets and subset down to target markets\n",
    "    markets_df = Coinmetrics.pullAndFormRelevantMarkets(exchanges_df, assets_df, BASE_URL, BASE_PARAMS, asset_universe)\n",
    "\n",
    "    # pull reference rates for USDC and USDT to use for exchange rate calculations\n",
    "    usd_df = Coinmetrics.pullAssetMetrics(BASE_URL, BASE_PARAMS, assets_df, STUDY_START, STUDY_END, \n",
    "                                          TARGET_FREQ, ['usdc', 'usdt'], ['ReferenceRateUSD'])\n",
    "    usd_df = Coinmetrics.cleanUSDPrices(usd_df, TARGET_FREQ)\n",
    "\n",
    "    # pull prices and volumes for all markets of interest\n",
    "    ohlcv_df = Coinmetrics.pullOHLCV(BASE_URL, BASE_PARAMS, STUDY_START, STUDY_END, TARGET_FREQ, markets_df)\n",
    "\n",
    "    # pull asset metrics\n",
    "    panel_df = Coinmetrics.pullAssetMetrics(BASE_URL, BASE_PARAMS, assets_df, STUDY_START, STUDY_END,\n",
    "                                            TARGET_FREQ, asset_universe, TARGET_METRICS)\n",
    "    panel_df = Coinmetrics.cleanPanel(panel_df)\n",
    "\n",
    "    # pull exchange metrics\n",
    "    ex_metrics_df = Coinmetrics.pullExchangeMetrics(BASE_URL, BASE_PARAMS, TARGET_EXCHANGE_METRICS, \n",
    "                                                    STUDY_START, STUDY_END, TARGET_FREQ)\n",
    "    ex_metrics_df = Coinmetrics.cleanExchangeMetrics(ex_metrics_df, TARGET_EXCHANGE_METRICS, TARGET_US_EXCHANGES)\n",
    "\n",
    "    # form macro dataframe\n",
    "    macro_df = usd_df.merge(ex_metrics_df, on=['date'], how='outer', validate='one_to_one')\n",
    "    macro_df.to_pickle(MACRO_OUT_FP)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.51 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.26 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.88 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.92 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.56 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.19 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.25 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.93 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.99 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.74 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.00 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.24 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.74 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out.\n",
      "Retrying after 5.25 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.40 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.64 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.72 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.07 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.34 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.08 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.30 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.49 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.98 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.21 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.99 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.74 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.69 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.55 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.61 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.72 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.20 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.66 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.58 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.21 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.74 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.60 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.97 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.60 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.92 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.06 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.38 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.29 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.46 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.92 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.23 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.29 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.64 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 3.17 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.78 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.23 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.50 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 3.86 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.71 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.20 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 3.34 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.94 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.02 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.68 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.96 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.74 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 3.99 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.45 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.00 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.50 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 3.24 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.72 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.63 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out.\n",
      "Retrying after 2.84 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.07 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.60 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.65 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.29 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.50 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 5.72 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 8.92 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.42 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.08 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.76 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.53 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 4.32 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 16.81 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.16 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 2.46 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.66 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.78 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.09 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 4.06 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.99 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.96 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 4.72 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.15 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.33 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.27 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.94 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.36 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.82 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 3.51 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.65 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.74 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.22 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.03 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.84 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.26 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.66 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.81 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.21 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.20 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.09 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.82 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.72 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.80 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.07 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.77 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.19 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out.\n",
      "Retrying after 2.78 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.28 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.05 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.90 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.08 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.36 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.38 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.17 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.33 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.57 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.52 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.91 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.16 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.68 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.68 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.19 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.80 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.91 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 2.86 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.18 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.41 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.65 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.26 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.15 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.24 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.27 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.06 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.92 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.62 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.82 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.54 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.41 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.79 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 0.61 seconds.\n",
      "The API call failed with error: HTTPSConnectionPool(host='api.coinmetrics.io', port=443): Read timed out. (read timeout=5)\n",
      "Retrying after 1.48 seconds.\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[19], line 2\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[39m# pull bid ask prices\u001b[39;00m\n\u001b[0;32m----> 2\u001b[0m ba_df \u001b[39m=\u001b[39m Coinmetrics\u001b[39m.\u001b[39;49mpullBidAsk(BASE_URL, BASE_PARAMS, STUDY_START, STUDY_END, markets_df)\n",
      "File \u001b[0;32m~/Dropbox/2-creations/2-crafts/4-i_research/2-research/2022-jmp/crypto_asset_pricing/code/helper_functions.py:1355\u001b[0m, in \u001b[0;36mCoinmetrics.pullBidAsk\u001b[0;34m(base_url, base_params, study_start, study_end, markets_df)\u001b[0m\n\u001b[1;32m   1353\u001b[0m params[\u001b[39m'\u001b[39m\u001b[39mstart_time\u001b[39m\u001b[39m'\u001b[39m] \u001b[39m=\u001b[39m time_list[j]\n\u001b[1;32m   1354\u001b[0m params[\u001b[39m'\u001b[39m\u001b[39mend_time\u001b[39m\u001b[39m'\u001b[39m] \u001b[39m=\u001b[39m time_list[j\u001b[39m+\u001b[39m\u001b[39m1\u001b[39m]\n\u001b[0;32m-> 1355\u001b[0m response_json \u001b[39m=\u001b[39m Helper\u001b[39m.\u001b[39;49mmakeApiCall(url, headers\u001b[39m=\u001b[39;49m{}, params\u001b[39m=\u001b[39;49mparams)\n\u001b[1;32m   1356\u001b[0m \u001b[39mif\u001b[39;00m (response_json \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m) \u001b[39m&\u001b[39m (\u001b[39mlen\u001b[39m(response_json[\u001b[39m'\u001b[39m\u001b[39mdata\u001b[39m\u001b[39m'\u001b[39m]) \u001b[39m>\u001b[39m \u001b[39m0\u001b[39m):\n\u001b[1;32m   1357\u001b[0m     \u001b[39m# convert to DataFrame\u001b[39;00m\n\u001b[1;32m   1358\u001b[0m     temp_df \u001b[39m=\u001b[39m pd\u001b[39m.\u001b[39mDataFrame(response_json[\u001b[39m'\u001b[39m\u001b[39mdata\u001b[39m\u001b[39m'\u001b[39m])\n",
      "File \u001b[0;32m~/Dropbox/2-creations/2-crafts/4-i_research/2-research/2022-jmp/crypto_asset_pricing/code/helper_functions.py:38\u001b[0m, in \u001b[0;36mHelper.makeApiCall\u001b[0;34m(url, headers, params, retries, timeout)\u001b[0m\n\u001b[1;32m     36\u001b[0m \u001b[39mfor\u001b[39;00m attempt \u001b[39min\u001b[39;00m \u001b[39mrange\u001b[39m(retries):\n\u001b[1;32m     37\u001b[0m     \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m---> 38\u001b[0m         response \u001b[39m=\u001b[39m requests\u001b[39m.\u001b[39;49mget(url, headers\u001b[39m=\u001b[39;49mheaders, params\u001b[39m=\u001b[39;49mparams, timeout\u001b[39m=\u001b[39;49m\u001b[39m8\u001b[39;49m)\n\u001b[1;32m     39\u001b[0m         response\u001b[39m.\u001b[39mraise_for_status()\n\u001b[1;32m     40\u001b[0m         \u001b[39mreturn\u001b[39;00m response\u001b[39m.\u001b[39mjson()\n",
      "File \u001b[0;32m~/miniconda3/envs/tf/lib/python3.10/site-packages/requests/api.py:73\u001b[0m, in \u001b[0;36mget\u001b[0;34m(url, params, **kwargs)\u001b[0m\n\u001b[1;32m     62\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mget\u001b[39m(url, params\u001b[39m=\u001b[39m\u001b[39mNone\u001b[39;00m, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs):\n\u001b[1;32m     63\u001b[0m \u001b[39m    \u001b[39m\u001b[39mr\u001b[39m\u001b[39m\"\"\"Sends a GET request.\u001b[39;00m\n\u001b[1;32m     64\u001b[0m \n\u001b[1;32m     65\u001b[0m \u001b[39m    :param url: URL for the new :class:`Request` object.\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m     70\u001b[0m \u001b[39m    :rtype: requests.Response\u001b[39;00m\n\u001b[1;32m     71\u001b[0m \u001b[39m    \"\"\"\u001b[39;00m\n\u001b[0;32m---> 73\u001b[0m     \u001b[39mreturn\u001b[39;00m request(\u001b[39m\"\u001b[39;49m\u001b[39mget\u001b[39;49m\u001b[39m\"\u001b[39;49m, url, params\u001b[39m=\u001b[39;49mparams, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n",
      "File \u001b[0;32m~/miniconda3/envs/tf/lib/python3.10/site-packages/requests/api.py:59\u001b[0m, in \u001b[0;36mrequest\u001b[0;34m(method, url, **kwargs)\u001b[0m\n\u001b[1;32m     55\u001b[0m \u001b[39m# By using the 'with' statement we are sure the session is closed, thus we\u001b[39;00m\n\u001b[1;32m     56\u001b[0m \u001b[39m# avoid leaving sockets open which can trigger a ResourceWarning in some\u001b[39;00m\n\u001b[1;32m     57\u001b[0m \u001b[39m# cases, and look like a memory leak in others.\u001b[39;00m\n\u001b[1;32m     58\u001b[0m \u001b[39mwith\u001b[39;00m sessions\u001b[39m.\u001b[39mSession() \u001b[39mas\u001b[39;00m session:\n\u001b[0;32m---> 59\u001b[0m     \u001b[39mreturn\u001b[39;00m session\u001b[39m.\u001b[39;49mrequest(method\u001b[39m=\u001b[39;49mmethod, url\u001b[39m=\u001b[39;49murl, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n",
      "File \u001b[0;32m~/miniconda3/envs/tf/lib/python3.10/site-packages/requests/sessions.py:587\u001b[0m, in \u001b[0;36mSession.request\u001b[0;34m(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)\u001b[0m\n\u001b[1;32m    582\u001b[0m send_kwargs \u001b[39m=\u001b[39m {\n\u001b[1;32m    583\u001b[0m     \u001b[39m\"\u001b[39m\u001b[39mtimeout\u001b[39m\u001b[39m\"\u001b[39m: timeout,\n\u001b[1;32m    584\u001b[0m     \u001b[39m\"\u001b[39m\u001b[39mallow_redirects\u001b[39m\u001b[39m\"\u001b[39m: allow_redirects,\n\u001b[1;32m    585\u001b[0m }\n\u001b[1;32m    586\u001b[0m send_kwargs\u001b[39m.\u001b[39mupdate(settings)\n\u001b[0;32m--> 587\u001b[0m resp \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49msend(prep, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49msend_kwargs)\n\u001b[1;32m    589\u001b[0m \u001b[39mreturn\u001b[39;00m resp\n",
      "File \u001b[0;32m~/miniconda3/envs/tf/lib/python3.10/site-packages/requests/sessions.py:701\u001b[0m, in \u001b[0;36mSession.send\u001b[0;34m(self, request, **kwargs)\u001b[0m\n\u001b[1;32m    698\u001b[0m start \u001b[39m=\u001b[39m preferred_clock()\n\u001b[1;32m    700\u001b[0m \u001b[39m# Send the request\u001b[39;00m\n\u001b[0;32m--> 701\u001b[0m r \u001b[39m=\u001b[39m adapter\u001b[39m.\u001b[39;49msend(request, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n\u001b[1;32m    703\u001b[0m \u001b[39m# Total elapsed time of the request (approximately)\u001b[39;00m\n\u001b[1;32m    704\u001b[0m elapsed \u001b[39m=\u001b[39m preferred_clock() \u001b[39m-\u001b[39m start\n",
      "File \u001b[0;32m~/miniconda3/envs/tf/lib/python3.10/site-packages/requests/adapters.py:489\u001b[0m, in \u001b[0;36mHTTPAdapter.send\u001b[0;34m(self, request, stream, timeout, verify, cert, proxies)\u001b[0m\n\u001b[1;32m    487\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m    488\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m chunked:\n\u001b[0;32m--> 489\u001b[0m         resp \u001b[39m=\u001b[39m conn\u001b[39m.\u001b[39;49murlopen(\n\u001b[1;32m    490\u001b[0m             method\u001b[39m=\u001b[39;49mrequest\u001b[39m.\u001b[39;49mmethod,\n\u001b[1;32m    491\u001b[0m             url\u001b[39m=\u001b[39;49murl,\n\u001b[1;32m    492\u001b[0m             body\u001b[39m=\u001b[39;49mrequest\u001b[39m.\u001b[39;49mbody,\n\u001b[1;32m    493\u001b[0m             headers\u001b[39m=\u001b[39;49mrequest\u001b[39m.\u001b[39;49mheaders,\n\u001b[1;32m    494\u001b[0m             redirect\u001b[39m=\u001b[39;49m\u001b[39mFalse\u001b[39;49;00m,\n\u001b[1;32m    495\u001b[0m             assert_same_host\u001b[39m=\u001b[39;49m\u001b[39mFalse\u001b[39;49;00m,\n\u001b[1;32m    496\u001b[0m             preload_content\u001b[39m=\u001b[39;49m\u001b[39mFalse\u001b[39;49;00m,\n\u001b[1;32m    497\u001b[0m             decode_content\u001b[39m=\u001b[39;49m\u001b[39mFalse\u001b[39;49;00m,\n\u001b[1;32m    498\u001b[0m             retries\u001b[39m=\u001b[39;49m\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mmax_retries,\n\u001b[1;32m    499\u001b[0m             timeout\u001b[39m=\u001b[39;49mtimeout,\n\u001b[1;32m    500\u001b[0m         )\n\u001b[1;32m    502\u001b[0m     \u001b[39m# Send the request.\u001b[39;00m\n\u001b[1;32m    503\u001b[0m     \u001b[39melse\u001b[39;00m:\n\u001b[1;32m    504\u001b[0m         \u001b[39mif\u001b[39;00m \u001b[39mhasattr\u001b[39m(conn, \u001b[39m\"\u001b[39m\u001b[39mproxy_pool\u001b[39m\u001b[39m\"\u001b[39m):\n",
      "File \u001b[0;32m~/miniconda3/envs/tf/lib/python3.10/site-packages/urllib3/connectionpool.py:703\u001b[0m, in \u001b[0;36mHTTPConnectionPool.urlopen\u001b[0;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)\u001b[0m\n\u001b[1;32m    700\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_prepare_proxy(conn)\n\u001b[1;32m    702\u001b[0m \u001b[39m# Make the request on the httplib connection object.\u001b[39;00m\n\u001b[0;32m--> 703\u001b[0m httplib_response \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_make_request(\n\u001b[1;32m    704\u001b[0m     conn,\n\u001b[1;32m    705\u001b[0m     method,\n\u001b[1;32m    706\u001b[0m     url,\n\u001b[1;32m    707\u001b[0m     timeout\u001b[39m=\u001b[39;49mtimeout_obj,\n\u001b[1;32m    708\u001b[0m     body\u001b[39m=\u001b[39;49mbody,\n\u001b[1;32m    709\u001b[0m     headers\u001b[39m=\u001b[39;49mheaders,\n\u001b[1;32m    710\u001b[0m     chunked\u001b[39m=\u001b[39;49mchunked,\n\u001b[1;32m    711\u001b[0m )\n\u001b[1;32m    713\u001b[0m \u001b[39m# If we're going to release the connection in ``finally:``, then\u001b[39;00m\n\u001b[1;32m    714\u001b[0m \u001b[39m# the response doesn't need to know about the connection. Otherwise\u001b[39;00m\n\u001b[1;32m    715\u001b[0m \u001b[39m# it will also try to release it and we'll have a double-release\u001b[39;00m\n\u001b[1;32m    716\u001b[0m \u001b[39m# mess.\u001b[39;00m\n\u001b[1;32m    717\u001b[0m response_conn \u001b[39m=\u001b[39m conn \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m release_conn \u001b[39melse\u001b[39;00m \u001b[39mNone\u001b[39;00m\n",
      "File \u001b[0;32m~/miniconda3/envs/tf/lib/python3.10/site-packages/urllib3/connectionpool.py:449\u001b[0m, in \u001b[0;36mHTTPConnectionPool._make_request\u001b[0;34m(self, conn, method, url, timeout, chunked, **httplib_request_kw)\u001b[0m\n\u001b[1;32m    444\u001b[0m             httplib_response \u001b[39m=\u001b[39m conn\u001b[39m.\u001b[39mgetresponse()\n\u001b[1;32m    445\u001b[0m         \u001b[39mexcept\u001b[39;00m \u001b[39mBaseException\u001b[39;00m \u001b[39mas\u001b[39;00m e:\n\u001b[1;32m    446\u001b[0m             \u001b[39m# Remove the TypeError from the exception chain in\u001b[39;00m\n\u001b[1;32m    447\u001b[0m             \u001b[39m# Python 3 (including for exceptions like SystemExit).\u001b[39;00m\n\u001b[1;32m    448\u001b[0m             \u001b[39m# Otherwise it looks like a bug in the code.\u001b[39;00m\n\u001b[0;32m--> 449\u001b[0m             six\u001b[39m.\u001b[39;49mraise_from(e, \u001b[39mNone\u001b[39;49;00m)\n\u001b[1;32m    450\u001b[0m \u001b[39mexcept\u001b[39;00m (SocketTimeout, BaseSSLError, SocketError) \u001b[39mas\u001b[39;00m e:\n\u001b[1;32m    451\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_raise_timeout(err\u001b[39m=\u001b[39me, url\u001b[39m=\u001b[39murl, timeout_value\u001b[39m=\u001b[39mread_timeout)\n",
      "File \u001b[0;32m<string>:3\u001b[0m, in \u001b[0;36mraise_from\u001b[0;34m(value, from_value)\u001b[0m\n",
      "File \u001b[0;32m~/miniconda3/envs/tf/lib/python3.10/site-packages/urllib3/connectionpool.py:444\u001b[0m, in \u001b[0;36mHTTPConnectionPool._make_request\u001b[0;34m(self, conn, method, url, timeout, chunked, **httplib_request_kw)\u001b[0m\n\u001b[1;32m    441\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mTypeError\u001b[39;00m:\n\u001b[1;32m    442\u001b[0m     \u001b[39m# Python 3\u001b[39;00m\n\u001b[1;32m    443\u001b[0m     \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> 444\u001b[0m         httplib_response \u001b[39m=\u001b[39m conn\u001b[39m.\u001b[39;49mgetresponse()\n\u001b[1;32m    445\u001b[0m     \u001b[39mexcept\u001b[39;00m \u001b[39mBaseException\u001b[39;00m \u001b[39mas\u001b[39;00m e:\n\u001b[1;32m    446\u001b[0m         \u001b[39m# Remove the TypeError from the exception chain in\u001b[39;00m\n\u001b[1;32m    447\u001b[0m         \u001b[39m# Python 3 (including for exceptions like SystemExit).\u001b[39;00m\n\u001b[1;32m    448\u001b[0m         \u001b[39m# Otherwise it looks like a bug in the code.\u001b[39;00m\n\u001b[1;32m    449\u001b[0m         six\u001b[39m.\u001b[39mraise_from(e, \u001b[39mNone\u001b[39;00m)\n",
      "File \u001b[0;32m~/miniconda3/envs/tf/lib/python3.10/http/client.py:1374\u001b[0m, in \u001b[0;36mHTTPConnection.getresponse\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1372\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m   1373\u001b[0m     \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m-> 1374\u001b[0m         response\u001b[39m.\u001b[39;49mbegin()\n\u001b[1;32m   1375\u001b[0m     \u001b[39mexcept\u001b[39;00m \u001b[39mConnectionError\u001b[39;00m:\n\u001b[1;32m   1376\u001b[0m         \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mclose()\n",
      "File \u001b[0;32m~/miniconda3/envs/tf/lib/python3.10/http/client.py:318\u001b[0m, in \u001b[0;36mHTTPResponse.begin\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    316\u001b[0m \u001b[39m# read until we get a non-100 response\u001b[39;00m\n\u001b[1;32m    317\u001b[0m \u001b[39mwhile\u001b[39;00m \u001b[39mTrue\u001b[39;00m:\n\u001b[0;32m--> 318\u001b[0m     version, status, reason \u001b[39m=\u001b[39m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_read_status()\n\u001b[1;32m    319\u001b[0m     \u001b[39mif\u001b[39;00m status \u001b[39m!=\u001b[39m CONTINUE:\n\u001b[1;32m    320\u001b[0m         \u001b[39mbreak\u001b[39;00m\n",
      "File \u001b[0;32m~/miniconda3/envs/tf/lib/python3.10/http/client.py:279\u001b[0m, in \u001b[0;36mHTTPResponse._read_status\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    278\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m_read_status\u001b[39m(\u001b[39mself\u001b[39m):\n\u001b[0;32m--> 279\u001b[0m     line \u001b[39m=\u001b[39m \u001b[39mstr\u001b[39m(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mfp\u001b[39m.\u001b[39;49mreadline(_MAXLINE \u001b[39m+\u001b[39;49m \u001b[39m1\u001b[39;49m), \u001b[39m\"\u001b[39m\u001b[39miso-8859-1\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[1;32m    280\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mlen\u001b[39m(line) \u001b[39m>\u001b[39m _MAXLINE:\n\u001b[1;32m    281\u001b[0m         \u001b[39mraise\u001b[39;00m LineTooLong(\u001b[39m\"\u001b[39m\u001b[39mstatus line\u001b[39m\u001b[39m\"\u001b[39m)\n",
      "File \u001b[0;32m~/miniconda3/envs/tf/lib/python3.10/socket.py:705\u001b[0m, in \u001b[0;36mSocketIO.readinto\u001b[0;34m(self, b)\u001b[0m\n\u001b[1;32m    703\u001b[0m \u001b[39mwhile\u001b[39;00m \u001b[39mTrue\u001b[39;00m:\n\u001b[1;32m    704\u001b[0m     \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m--> 705\u001b[0m         \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_sock\u001b[39m.\u001b[39;49mrecv_into(b)\n\u001b[1;32m    706\u001b[0m     \u001b[39mexcept\u001b[39;00m timeout:\n\u001b[1;32m    707\u001b[0m         \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_timeout_occurred \u001b[39m=\u001b[39m \u001b[39mTrue\u001b[39;00m\n",
      "File \u001b[0;32m~/miniconda3/envs/tf/lib/python3.10/ssl.py:1274\u001b[0m, in \u001b[0;36mSSLSocket.recv_into\u001b[0;34m(self, buffer, nbytes, flags)\u001b[0m\n\u001b[1;32m   1270\u001b[0m     \u001b[39mif\u001b[39;00m flags \u001b[39m!=\u001b[39m \u001b[39m0\u001b[39m:\n\u001b[1;32m   1271\u001b[0m         \u001b[39mraise\u001b[39;00m \u001b[39mValueError\u001b[39;00m(\n\u001b[1;32m   1272\u001b[0m           \u001b[39m\"\u001b[39m\u001b[39mnon-zero flags not allowed in calls to recv_into() on \u001b[39m\u001b[39m%s\u001b[39;00m\u001b[39m\"\u001b[39m \u001b[39m%\u001b[39m\n\u001b[1;32m   1273\u001b[0m           \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m\u001b[39m__class__\u001b[39m)\n\u001b[0;32m-> 1274\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mread(nbytes, buffer)\n\u001b[1;32m   1275\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[1;32m   1276\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39msuper\u001b[39m()\u001b[39m.\u001b[39mrecv_into(buffer, nbytes, flags)\n",
      "File \u001b[0;32m~/miniconda3/envs/tf/lib/python3.10/ssl.py:1130\u001b[0m, in \u001b[0;36mSSLSocket.read\u001b[0;34m(self, len, buffer)\u001b[0m\n\u001b[1;32m   1128\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m   1129\u001b[0m     \u001b[39mif\u001b[39;00m buffer \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n\u001b[0;32m-> 1130\u001b[0m         \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_sslobj\u001b[39m.\u001b[39;49mread(\u001b[39mlen\u001b[39;49m, buffer)\n\u001b[1;32m   1131\u001b[0m     \u001b[39melse\u001b[39;00m:\n\u001b[1;32m   1132\u001b[0m         \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_sslobj\u001b[39m.\u001b[39mread(\u001b[39mlen\u001b[39m)\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "# pull bid ask prices\n",
    "ba_df = Coinmetrics.pullBidAsk(BASE_URL, BASE_PARAMS, STUDY_START, STUDY_END, markets_df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# form the panel\n",
    "prices_df = Coinmetrics.cleanMarketPanels(ohlcv_df, TARGET_FREQ, markets_df, usd_df, ba_df)\n",
    "panel_df = panel_df.merge(prices_df, on=['date', 'asset'], how='outer', validate='one_to_one')\n",
    "panel_df.to_pickle(PANEL_OUT_FP)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "tf",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "e428bc405edc59f3352e9792cab27c5e28560f7efb4b47308a6c6ea38cd15df2"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
